language: ruby
rvm:
  - 2.2.0
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database real_estate_test;' -U postgres
  - psql -c "CREATE USER real_estate WITH PASSWORD 'password1';" -U postgres
