source 'https://rubygems.org'

ruby '2.2.0'
gem 'rails', '4.2.3'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'puma'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'autoprefixer-rails'
gem 'coveralls', require: false
gem 'badgerbadgerbadger'
gem 'dotenv-rails', require: 'dotenv/rails-now'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-linkedin'
gem 'omniauth-instagram'
gem 'koala', '~> 2.2'
gem 'font-awesome-sass'
gem 'paranoia'
gem 'fog'
gem 'carrierwave'
gem 'twitter'
gem 'mandrill-api'
gem 'sidekiq'
gem 'devise-async'
gem 'sinatra', require: false
gem 'remotipart'
gem 'gon'
gem 'rails_12factor'
gem 'lightbox2-rails'

group :development, :local, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'pry-rails'
  gem 'sextant'
  gem 'better_errors'
  gem 'faker'
  gem 'parallel_tests'
end

group :test do
  gem 'fuubar'
  gem 'rspec-rails', '~> 3.0'
  gem 'capybara'
  gem 'poltergeist'
  gem 'launchy'
  gem 'shoulda-matchers'
  gem 'email_spec'
  gem 'rspec-sidekiq'
  gem 'selenium-webdriver'
  gem 'database_cleaner'
  gem 'vcr'
  gem 'webmock'
  gem 'capybara-mechanize'
end
